# print('umesh' * 5)
# print(int(1.1))
# print(int(1.9))
# print(int(True))
# print(int(False))
# print(type(int('1')))
# print(int('1') + int('1'))
# print(float(1))
# print(float('1.1') + float('1.1'))
# print(float(True))
# print(float(False))
# print(str(1))
# print(str(True) + str(True))
# print(str('1.1') + str('1.1'))
# print(bool(0))
# a = input('Enter first number : ')
# b = input('Enter second number : ')
a = int(input('Enter first number : '))
b = int(input('Enter second number : '))
print(int(a) + int(b))
print(int(a) - int(b))
print(int(a) * int(b))